version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm test
  steve:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double Trouble"
workflows:
  version: 2.1
  bobby_sally:
    jobs:
      - bobby
      - sally
      - steve
